# This docker compose is solely for dev purposes. It does not include application containers and just needed 3rd party services like DBs.

version: '3.7'
services:
  postgres01:
    image: postgres:latest
    hostname: "postgres01"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev_db
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev_db"]
      interval: 10s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - "postgres01_data:/var/lib/postgresql/data"


volumes:
  postgres01_data:

networks:
  internal:

